### ISSUE TITLE
Showing at max 8 columns/tracks and optimizing view for this setting

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#11]
Switching track views in steps of 8 tracks
1..8 (or 0..7)
9..16 (or 8..15)
...

**Comment by JoepVanlier** [comment]
You mean shortcuts to jump to 1.8 or what? Because I personally like the dragging to size.

**Comment by michaelsjackson** [comment]
Ok this is not so important, usually, most times I would not need more than 8 tracks I guess.

**Comment by JoepVanlier** [comment]
I am planning to make it store the last window size like in HT, after that you only have to size it once and it should remember it.
