### ISSUE TITLE
Color highlighting in first column, is not always correct, when scrolling beyond first window length

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#12]
After scrolling to second and higher pages of excel table, something goes wrong with the color highlighting of first column, where each 4th row gets a different color emphasis.

I recognize this often, when I look to those colors for pattern placement, to discover later they are not all starting at bar positions, which they should...

**Comment by michaelsjackson** [comment]
First row is always highlighted, which is correct for starting position (line 0), but if you scroll further, until first line is 16, then this line 16 also gets highlighted, I think is is the source of the problem.
if (first line number modulo 64 is zero)
   then do first column highlighting
could do the trick.

**Comment by JoepVanlier** [comment]
Should be fixed in b4e7b7eb738c0bdd9920bfc8f0e4d6029b84c032
