### ISSUE TITLE
Mousewheel scrolling in steps of 4 lines, shift-mousewheel scrolling in steps of 1 line

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#13]
Improvement idea. Fine scrolling in single lines using shift-mousewheel, normal mousewheel would scroll in steps of 4 lines which equals to 1 bar scrolling, for quick bar correct placements of patterns.

**Comment by JoepVanlier** [comment]
Good idea. Added in b4e7b7eb738c0bdd9920bfc8f0e4d6029b84c032.
