### ISSUE TITLE
Track selection in hackey patterns could select track in TCP of Reaper

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#14]
And bring that track to view. Thus while moving in hackey patterns, the arrange would move in parallel and you would always see your edits in arrange.

In short: Reaper arrange view follows cursor of hackey patterns. Scrolling down could even scroll the Reaper arrange to the side, as a bonus.

**Comment by JoepVanlier** [comment]
Good idea, as an option anyway. I will see how feasible this is.

**Comment by JoepVanlier** [comment]
This was added in dfeb18a57e938726f00c897d8b3ce56567ad4174

I made it optional (option dialog is not yet implemented) considering that the track focus part of this had to be done in a relatively hacky way (as far as I know, there is no API command to focus one specific track, only to move along them). I'm not quite sure yet how robust it is.

**Comment by michaelsjackson** [comment]
That is why its name is hackey patterns. It seems to work great. I guess there are actions for selecting tracks directly, e.g. tracks 1..99, those might help as well, at least for robustness among those tracks.

Track: Select track 99

**Comment by michaelsjackson** [comment]
If you continue development in this speed, this will blow away soon even jeskola buzz, together with Reaper in the background  :)
