### ISSUE TITLE
Running on empty arrange gives attempt to index a nil value

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#16]
line 1392:
![hackey_patterns_v021_running_on_empty_arrange](https://user-images.githubusercontent.com/5049512/46593816-1db14d00-cacf-11e8-92b0-8f02bc5f05a5.png)

**Comment by JoepVanlier** [comment]
Should be fixed in d190898a4437c3ed2136ce0a8a191ad40d573f87
