### ISSUE TITLE
Patterns could get default prefix names (same as triggering key) by default

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#17]
... to prevent cases as this:

 https://www.youtube.com/watch?v=NEQDyQ0vLv4 

In short: Even if items/patterns have no names, you would see something in the excel table, so if you change the item, you would see it, otherwise, as in the video above, we can hear the difference but can not see the item name, if it has no name.

**Comment by JoepVanlier** [comment]
Fixed in d190898a4437c3ed2136ce0a8a191ad40d573f87

**Comment by michaelsjackson** [comment]
Sorry for commenting here, it works almost perfectly. prefix could be zero based. Instead of i, i-1.
