### ISSUE TITLE
Opening hackey trackey using ENTER, then TAB, seems to crash hackey trackey

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#18]
At least it did just now. So it might be a hackey trackey bug as well.

**Comment by JoepVanlier** [comment]
Crash how?
What error do you get?
What happens?

**Comment by michaelsjackson** [comment]
I can not reproduce it, you can close it again. I can report again if it happens again in a reproducable form.
