### ISSUE TITLE
Showing muted items in darker color, in excel table

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#20]
Hackey patterns could show muted items in darker color. Muting would happen elsewhere, or in arrange, but at least we would additionally see in hackey patterns which items are muted. Currently, in v0.23, even if I mute an item in arrange, it shows in hackey patterns with same color as all the unmuted items. This would help a little more in understanding what is playing currently and what not.

**Comment by JoepVanlier** [comment]
Added in 570e5f58abc5215533205e659525366b6c0148b5
