### ISSUE TITLE
patterns shows only black, not sure why

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#26]
I changed a few themes, then later somehow, hackey patterns shows only black color. Currently I can not use hackey patterns.

**Comment by michaelsjackson** [comment]
Tried changing theme from 'renoise' to 'buzz', still same problem. Nothing is drawn, only the background color is visible.

**Comment by JoepVanlier** [comment]
Screenshot?

**Comment by michaelsjackson** [comment]
![hackey_patterns_v024_drawing_bug](https://user-images.githubusercontent.com/5049512/46859667-abae7000-ce0e-11e8-9319-f435642664ea.png)

**Comment by michaelsjackson** [comment]
Here the content of my seq.cfg:

> followRow=1
> theme=buzz
> nameSize=160
> largeScroll=4
> page=4
> nChars=9
> automation=1
> boxsize=8
> zoom=0.25
> patternLines=30
> followTrackSelection=1
>

**Comment by JoepVanlier** [comment]
Thanks! I will look into it.

**Comment by JoepVanlier** [comment]
Can try 9194d48ad59a986d0736484868a38cd12b2a7fe1 . Does it display stuff again?

There are also OFF markers now, but Hackey Trackey is not yet able to deal with these tiny MIDI items I noticed. I am aware of the issues with that (causes an error when HT is opened on an OFF/break item).

**Comment by michaelsjackson** [comment]
Still showing only background color here.

**Comment by michaelsjackson** [comment]
Returned back to v0.23 for now... without theme switching.

**Comment by michaelsjackson** [comment]
you changed from

`seq.cfg.eps           = 0.000001
`
to

`seq.eps           = 0.000001`

Could this be the reason?

**Comment by JoepVanlier** [comment]
Are you certain you were on v0.25? The last version did work for me on Ubuntu whereas v0.24 did not.

And no. That has to do with the margin of error of matching up items to row.

**Comment by michaelsjackson** [comment]
Yes, it was v0.25.

**Comment by JoepVanlier** [comment]
Hmmm. That's interesting.

Could you try the versions I am attaching here to see if any of them work?

[HackeyPatterns_exec_nc_local.zip](https://github.com/JoepVanlier/Hackey-Patterns/files/2475619/HackeyPatterns_exec_nc_local.zip)

**Comment by JoepVanlier** [comment]
The other two? There's one more. The update flip one.

**Comment by michaelsjackson** [comment]
Maybe you could write a 'debug' version, with all the changes after 0.23, so we could toggle activation of those changes, one by one, trying to find out the causing part.

e.g. removing all theme parts, if this helps.
e.g. keeping only theme parts, as new addition, seeing if this works.
e.g. adding other stuff one by one, until we find the error source.

In short, not adding too many things at once, for debugging at least.

**Comment by michaelsjackson** [comment]
Could this be the reason?

```
-    local X = gfx.w - self.cfg.nameSize
-    local boxsize = self.cfg.boxsize
+    local X = gfx.w - cfg.nameSize
+    local boxsize = cfg.boxsize

```

Maybe it should be:
```


+    local X = gfx.w - self.nameSize
+    local boxsize = self.boxsize
```

**Comment by michaelsjackson** [comment]
Sometimes you use cfg as 'self.cfg', sometimes not, maybe there is some confusion somewhere?

Here you continue using self.cfg, as self.cfg.patternLines
```

+                local scroll = math.floor( self.fov.scrollpat * (#pNames - self.cfg.patternLines + 1) )
+                self:deleteFromPool(self.xpos, i+scroll)
```


Should it be then?
```

+                local scroll = math.floor( self.fov.scrollpat * (#pNames - cfg.patternLines + 1) )
+                self:deleteFromPool(self.xpos, i+scroll)
```

**Comment by michaelsjackson** [comment]
One of the below additions should be the source of the problem. Having for each a set of changes, we could toggle, would be perfect for testing.

```
+ * v0.24 (2018-10-10)
+   + Allow visualization of mute status.
+   + Improved renoise color scheme.
+   + Added zoom (+/-)
+   + Added panic (F12)
+   + Added theme switching (F11)
```

**Comment by michaelsjackson** [comment]
The strange thing, first it was working, then something happened I started getting this empty background, then it stood always like that.

**Comment by JoepVanlier** [comment]
I sometimes cache cfg locally to make things faster. This avoids going through the global namespace all the time. If you see cfg.blah, you should see local cfg = self.cfg somewhere higher up but within the same scope.

eps I deliberately moved out of cfg to not have issues with the formatting in the cfg file. It should really not affect rendering at all.

The thing is, what is weird that none of those things should break all of the rendering. I suspect there is something more unusual going on.

1. Could you try deleting or renaming your cfg files (seq.cfg and _wpos.cfg) just to exclude something went wrong with the configuration file? They should just be recreated automatically.

2. When you click and drag in the screen, is there still nothing displayed?

3. I suspect that somehow, there's something weird going on with the graphics loop. Could you try this one, here the buffer flip is in a different location:
[HackeyPatterns_exec_u2.zip](https://github.com/JoepVanlier/Hackey-Patterns/files/2476359/HackeyPatterns_exec_u2.zip)

**Comment by michaelsjackson** [comment]
Juhhey, it works. Not sure what helped. I did following:
- deleted both cfg files
- pasted your new exec_u2 version

Tried and it seems to work!
Maybe the solution was deleting the cfg files, maybe pasting of the new version. Thanks a lot. Later I can try the newly added features.

**Comment by JoepVanlier** [comment]
Cool.

**Comment by michaelsjackson** [comment]
Had this case today again, this time I did only this:
- deleted both cfg files
Luckily this helped. So it seems this is somehow related to the cfg files, not sure why and how?
