### ISSUE TITLE
Writing the text OFF, right aligned into the cell, if possible, so it hits the eye easier

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#28]
It is clearer separated visually, imo. But only a minor improvement, again imo. The OFF's will not disturb the eye, when looking at the numbers on the left side. Looks simpler overall.

**Comment by JoepVanlier** [comment]
Added in 366462f10edad4b9e41b605e3d9c09b3862e0a00
