### ISSUE TITLE
Mousewheel scrolling forward 16 lines, backward 4 lines

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#29]
I know this unequal scrolling concept from Totem (media player) in linux, e.g. you jump forward in steps of 1 mins, backward in steps of 15s, which is quarter of 1 minute.

Similarly, mousewheel could move 16 lines forward = 4 bars, backward 4 lines = 1 bar. Assuming 16 steps per bar.

Not a must, just one more finetuning idea. Jumping 4 bars is typical in hip-hop kind of music, or jumpstyle where changes happen each 4 bars. For other types like trance are 8 bars typical musical segments. This way, you could mouse jump in steps of typical musical segments, in above example 4 bars.

**Comment by JoepVanlier** [comment]
Added in 9f684397754c89c5ea55f86148985948732d7818

Look for largeScrollFwd and largeScrollBwd in the cfg file. Note that to update the cfg file for the new version, open Hackey Patterns once and close it immediately after.
