### ISSUE TITLE
Text OFF not visible if cell selected and OFF not fully right aligned

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#31]
Full right alignment of the text 'OFF' seems not to be possible, no problem.

**Comment by JoepVanlier** [comment]
Try b9942a07228f1d0dbe8bf5e5de6dbd4a8df0cd37 . Better?

**Comment by michaelsjackson** [comment]
Visibility works now, thanks a lot. Regarding right alignment here it looks as follows:
![auswahl_101](https://user-images.githubusercontent.com/5049512/47358360-d2e82580-d6c9-11e8-931c-1f23a5486397.png)
