### ISSUE TITLE
hackey-patterns ignores audio items?

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#33]
Just checked if rendered audio items are considered by hackey-patterns. (Just after rendering the initial midi composition to audio.) 

Unfortunately, hackey-patterns seems to ignore audio items. It would be too cool, if even audio items would be simply listed 0..9, a..z, having the advantage of easy placement, and adding OFF cuts. 

Example: You render only 1 bar of music, then want to copy it around at different places, adding mutes here and there using OFF. Quickly you could build some background variation. Because we created those loops from initial midi it should fit perfectly anyway.

Summary of advantages of this feature again:
(1)  easy copy paste in arrange
(2)  mutes via OFF

**Comment by JoepVanlier** [comment]
I'd like that, but it's very unlikely to happen any time soon. There's no pooled audio item.

**Comment by michaelsjackson** [comment]
I see, and making it as unpooled copies for audio items, would be against which principle?

Example: I render the 8 stereo outs as separate audio items, so they are somehow nicely separated anyway, like kick and snare separately from the rest: kick + snare + 6 more outs.  Using hackey trackey I could still play with effects on those outs. Using hackey patterns would allow copy+paste+OFF.

If all this makes not much sense, then no problem, we have to do it then on midi level. I was thinking about the audio variant, as shortcircuit 1.1.2 has problems saving its samples, so after each restart of the reaper project I have to select the right sample dir, so rendering it to audio would kind of solve this issue. But if I can not play around with copy+paste+OFF, then this would be also a limitation, kind of.  :-)

**Comment by JoepVanlier** [comment]
It would be inconsistent for one. But it's also not quite that simple. It would require quite a bit of extra stuff in how pools are handled and identified. This is not a modification that is easily made. First, I want to get the MIDI up to spec. There are still issues on that front to iron out. Hence the not any time soon.

But feel free to add it and do a pull request.

**Comment by JoepVanlier** [comment]
I may have some time to explore how it could work next weekend. Hashing the wave filename and using that as a GUID might work. Then the rest of the code could go through the same pipeline, which makes things a lot more convenient.

**Comment by michaelsjackson** [comment]
You always come up with genious solutions, wonderful, thanks a lot. Its time again to do some new Youtubes for the hackey friends. :)  If only shortcircuit would open directly it would be so good, I wanted to check using UsesWhat and FileMon (or something like that), which libraries, files, directories shortcircuit uses exactly, maybe it could help installing some native Win dll's for wine, but the correct ones, which are required for those sample directory finding.  Nobody else seems to have those problems or nobody uses shortcircuit in linux in wine.

**Comment by michaelsjackson** [comment]
Shortcircuit would be perfect experimentation partner for samples, together with its all filter options, and hackey patterns exact control of those.

**Comment by JoepVanlier** [comment]
Soooo... I don't know about shortcircuit, but you could try 6ba71f4eeb471873e95d73d256786fb37d1de46d . I have added support for PCM data (audio). I think it should work, but consider it an experimental feature for now. :)

**Comment by JoepVanlier** [comment]
Good good. Happy it works for you :+1: 

Closing this one now :)
