### ISSUE TITLE
Show only tracks which are not hidden in TCP

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#35]
Would it be possible showing only tracks in hackey patterns, which are not hidden in tcp? This would simplify the view in hackey patterns enormously. Binding it to the visibility in tcp would be most flexible approach I guess. 

I have already a binding for arrange for hiding track under mouse, anything I am not interested in while editing, I just hide, it is playing in the background, invisible but still hearable, in mcp I can see the track anyway, e.g. for further mixing. So hackey patterns would get same simplified view.

Just wanted to test the newly added track colors, but got only an error, wrote already in a separate issue.

Implementation could be something like:
```
if (track not invisible in tcp)
  add to hackey patterns
```

**Comment by JoepVanlier** [comment]
Added in 70b8e921508d16211c157d8f96278caa1e46e6ed .

If only it was that easy as your code example :D
It actually required a fair amount of refactoring, so be on the lookout for bugs! :)

**Comment by michaelsjackson** [comment]
Yes, bug.

...ripts\Hackey Sequencer\Sequencer\HackeyPatterns_exec.lua:1634: attempt to get length of a nil value (local 'patternNames')

**Comment by michaelsjackson** [comment]
But after closing, opening HP, it seems to work, just in the moment of hiding/deletion, if you were on a track which was hidden from tcp, then you get above error, it seems. Just tried that case before.

**Comment by JoepVanlier** [comment]
Ah okay. Anyways, that bug you had should be fixed in the last version.
