### ISSUE TITLE
patterns and trackey could use same config for window position and size

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#36]
I would prefer it if trackey and patterns would overlap, when toggling via ENTER. However I have to press ENTER twice, so the other window is closed again. Single ENTER, plus appearing exactly on same place as the other window would be perfect.

**Comment by JoepVanlier** [comment]
I don't want them to share a config file since it should be possible to install one without the other.

The location of HT is stored. Just close it once manually when it is in the desired position?
