### ISSUE TITLE
1634: attempt to get length of a nil value (local 'patternNames')

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#37]
...ripts\Hackey Sequencer\Sequencer\HackeyPatterns_exec.lua:1634: attempt to get length of a nil value (local 'patternNames')

**Comment by JoepVanlier** [comment]
Please give me more to go on. When you report a bug, tell me what you did, what you expected would happen and what actually happened. Without this, it's next to impossible to fix bugs.

**Comment by michaelsjackson** [comment]
If I write nothing, it means: I opened an old existing project, opened HP, then got this message.

**Comment by JoepVanlier** [comment]
That can be, but that doesn't help me debug what's happening for your specific project. The key to a good bug-report is trying to find reproducible conditions that cause it. If I can't replicate it on my side, I can't fix it.

**Comment by JoepVanlier** [comment]
I would appreciate it. The more information you can give me on what you were doing when the error occurred, the better.

**Comment by JoepVanlier** [comment]
I'm closing this one for now. If it happens again in a reproducible way, let me know.
