### ISSUE TITLE
   Integrated with Hackey Trackey (doubleclick a pattern in the sequencer), ENTER as alternative

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#4]
+ Integrated with Hackey Trackey (doubleclick a pattern in the sequencer)

Having ENTER for toggling between sequencer and tracker, as in buzz, as an alternative would be perfect!

Inside Reaper arrange I am using ENTER for toggling between arrange and midi editor.
Same for switching between sequencer and tracker would finish the perfect design.

In both cases you would switch from detailed editing and big picture overview/design.

**Comment by michaelsjackson** [comment]
`   if ( (ctime - self.lastLeftTime) < doubleClickInterval or inputs( 'enter' )) then
      self:startHT(self.xpos, self.ypos)`

**Comment by JoepVanlier** [comment]
No, don't put it where the mouse handling is. That condition won't get hit when you want it.

The keyboard handling is further down. Anyways, the key was added in b4e7b7eb738c0bdd9920bfc8f0e4d6029b84c032
