### ISSUE TITLE
Create new item with Ctrl-Enter

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#41]
> Added create new item (CTRL+DRAG)

Ctrl-Enter could do same, item length could be the loop region or using some default length like 1 or 2 or 4 bars, length of loop region would be most flexible I guess.

Workflow would be then as follows:
- set loop length anywhere
- navigate to where you want to create new item
- hit ctrl-enter

**Comment by JoepVanlier** [comment]
Good idea! Added in a516c2ee8eda715522e55b9b6addf85f50bc235b :)

Also added Ctrl + PgUp and PgDown to shift the loop by the loopsize. Might be useful for 4/4 music :)

**Comment by michaelsjackson** [comment]
The idea is directy from buzz or buze, one of both at least. Why inventing new ideas if there are already  over time established great ideas waiting to be implemented from those programs. Thanks for adding so quickly, as always.
