### ISSUE TITLE
Minor cosmetics, highlighted row goes beyond last column

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#43]
![auswahl_159](https://user-images.githubusercontent.com/5049512/48305044-12b16880-e524-11e8-96a9-631f95158ed5.png)

**Comment by JoepVanlier** [comment]
You are on 0.40 in the screenshot. Can you reproduce this in the latest version (0.46)?

**Comment by michaelsjackson** [comment]
I took your screenshot, as I remembered it was still there, but just checked now, indeed you corrected it. Sorry, now its perfect.
