### ISSUE TITLE
Rightmost column for patterns could get much thinner

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#45]
Now this column with pattern names occupies too wide space, as the title is so long, "Track patterns/items". I guess this is anyway clear or this could be just named as 'patterns', so it gets thinner, I would prefer even no title at all, and the patterns showing only numbers 00..99. Or offering two options.
(wide) as it is now
(thin)  showing no title, names as 00..99

Just another visuals improvement idea, trying to make everything more elegant, removing distracting elements, as much as possible.

**Comment by JoepVanlier** [comment]
In the latest commit, you can set tinyPatterns in the config to 1 to get this behaviour.

Also, you can drag the line to move the pattern position further to the right.

**Comment by michaelsjackson** [comment]
If you want you can close this, as the rightmost column is very thin for some time, thanks a lot.
