### ISSUE TITLE
When adding a new pattern in sequencer, sometimes it adds it (the number 01) one line above

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#5]
This happens usually at lower positions. I am sure you would find the error causing position in code much faster. Only the position in the sequencer grid is wrong, the placement in arrange seems to be correct.

Example: 
Placing a 1 bar pattern in sequencer at position/line 0 adds 4 lines, which is correct.
..., at position 64 adds 4 lines, which is correct.
..., at position 128 adds 5 lines, which is one line too much.
Maybe this example helps a little.

Strangely
..., at position 672 adds 4 lines, which is correct, again.

Now zero is zero is great, and not one. 

Tracks getting default track names in sequencer is great. (Track 00, Track 01...)

Double click opened hackey trackey great. ENTER doing this would be perfect. Same for switching back using ENTER.

**Comment by michaelsjackson** [comment]
Well, I am using Reaper 32 bit, in wine, in ubuntu 64bit.

**Comment by JoepVanlier** [comment]
Can you attach an RPP file where this happens?

**Comment by michaelsjackson** [comment]
Of course.

[hackey_patterns_016.RPP.zip](https://github.com/JoepVanlier/Hackey-Patterns/files/2453958/hackey_patterns_016.RPP.zip)


It seems almost in all cases, the placement on the excel table is one line above, all ending up in 5 lines, instead of correct 4 lines.

**Comment by michaelsjackson** [comment]
I guess, the error could have some relationship to page scrolling, so after you have scrolled down the view, below max line, then back up, the grid counting is not correct any more, thus placements occur on different positions. Maybe this helps a little.

**Comment by michaelsjackson** [comment]
I could even make a video / youtube, if it helps, how it looks here.

**Comment by michaelsjackson** [comment]
I really love this yellow line already.  .-)

**Comment by JoepVanlier** [comment]
Thanks for the RPP file. I see what you mean now. Fixed in 9761f73d1201d7dbc9cc80f6fa139c2c2346c8ae
