### ISSUE TITLE
Managing pooled pattern copies, as a backup, in a separate tab, would that be possible?

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#6]
New tab could be saved for project.RPP as 'project_pattern_pool.RPP'

This would keep the arrange clean, plus not having any side effects, if you used certain actions depending on position of last item in arrange.

**Comment by JoepVanlier** [comment]
Not possible. It seems you can't have pooled pastes over tab boundaries. As I rely on the GUID and paste command for identification, that's a no go.
