### ISSUE TITLE
Entire selected current line could be highlighted in a different light color

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#7]
Current line highlighting in sequencer.

**Comment by michaelsjackson** [comment]
With current line I mean the cursor in the excel table, now it highlights only the current cell with a darker color, this could be applied to the entire row, but in a lighter color, just to see in which line I am, in all columns. Then I could see easier if I would place the pattern in correct line, 192, for example.

**Comment by JoepVanlier** [comment]
Ahh okay. Sure, that can be done.

**Comment by michaelsjackson** [comment]
Thanks for superfast implementation. Works great!
