### ISSUE TITLE
Mousewheel is moving the cursor in sequencer, as in hackey trackey

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#9]
Could be handy if your right hand is anyway on the mouse, the left hand could sit on the key 0 for example.

**Comment by JoepVanlier** [comment]
Added in a5f73797b8fac125962d68c026215059d16c3e08

**Comment by michaelsjackson** [comment]
Working perfectly, thanks! What a development speed.
